### ISSUE TITLE
No AE2 Meteorites

### ISSUE THREAD

**Issue by Az0ni** [Kasax007/Dreamcraft-Development-#47]
We discovered a pretty large chunk of the map but didnt find any Applied Energistics 2 Meteorites so far. I dont know if its purpose or a bug.
Thx for looking it up.

Dreamcraft 1.19 v7

**Comment by DooDesch** [comment]
I found quite a few, our server is running since v14.
Altough I'm searching for them in the mining dimension, where you can get using the mining portal, which isn't pregenerated.
Maybe that would suit at least a workaround?
