### ISSUE TITLE
unable to use Sandwich Table due to Carrier mod

### ISSUE THREAD

**Issue by Secondbreakfastpip** [Kasax007/Dreamcraft-Development-#48]
Due to the mod Carrier using the controls "sneak+ rclick" and not having a key config, players are unable to use the Sandwichable mod's Sandwich Table which also uses the same controls and also has no config.

**To Reproduce**
1. Sneak + right click on a sandwich table with completed sandwich
2. Table is instead picked up

**Expected behavior**
Complete sandwich to drop from the sandwich table

**Version of the modpack**
1.19 fabric

**Comment by Kasax007** [comment]
It does have a key config. Look for this: 
![image](https://user-images.githubusercontent.com/92468253/187071940-3190626e-7d4e-47e8-bd51-81cc7dafbaf2.png)
