### ISSUE TITLE
Server Hangs and Crashes When Opening Some Chests

### ISSUE THREAD

**Issue by duckman** [Kasax007/Dreamcraft-Development-#51]
**Describe the bug**
Some chests in the oceans, like on ships, will freeze the server long enough to trigger the watchdog to crash and restart the server. I even quadrupled the max-tick-time and it still triggered after the new time.  My best guess is a treasure map is trying to generate.

**To Reproduce**
Find some chests in the ocean and open them until you find one that appears not to open. Everything stops moving and even chat stops working.

**Expected behavior**
Chest opens

**Screenshots + Crash log**
Server says "[Worker-Main-14/WARN]: Empty height range: [0 absolute--50 absolute]" when opening the chest.
[crash-2022-10-02_19.15.07-server.txt](https://github.com/Kasax007/Modpack-Development/files/9693311/crash-2022-10-02_19.15.07-server.txt)

**Version of the modpack**
1.19 Serverpack v19.zip

**Comment by TheMilso** [comment]
I am getting the same crash on my server as well.

[crash-2022-10-08_13.25.35-server.txt](https://github.com/Kasax007/Modpack-Development/files/9740069/crash-2022-10-08_13.25.35-server.txt)

**Comment by Kasax007** [comment]
I hope this is fixed in the new 1.19.2 version!

**Comment by Kasax007** [comment]
If not feel free to reopen the issue
