### ISSUE TITLE
Frequent Crashes on latest 1.19.2 version

### ISSUE THREAD

**Issue by srob650** [Kasax007/Dreamcraft-Development-#55]
**Describe the bug**
Crashing fairly often, seemingly when normal events happen.  Sometimes it's when going through a nether portal, sometimes when simply opening a crafting terminal.

**To Reproduce**
Unsure how to reproduce as I don't yet see a pattern, but I have a crash report attached.

**Version of the modpack**
1.19.2

I love this modpack so far, hopefully you can help as I want to keep playing it!
[crash-2022-11-01_15.14.08-client.txt](https://github.com/Kasax007/Modpack-Development/files/9914295/crash-2022-11-01_15.14.08-client.txt)

**Comment by Kasax007** [comment]
if the issue still persists on the new version feel free to reopen this.
