### ISSUE TITLE
something causing abnormally bad performance of internal server

### ISSUE THREAD

**Issue by DougStoker** [Kasax007/Dreamcraft-Development-#57]
<img width="1408" alt="Screen Shot 2022-11-07 at 8 39 53 PM" src="https://user-images.githubusercontent.com/40470811/200470913-4c0b4eff-c0bf-497a-8009-ff859697b1e4.png">

https://spark.lucko.me/Gn4Sz9ZSia
![2022-11-07_20 48 41](https://user-images.githubusercontent.com/40470811/200471230-c9ae4dc3-b854-48fa-984c-3c65ee6235a4.png)
<img width="599" alt="Screen Shot 2022-11-07 at 8 52 07 PM" src="https://user-images.githubusercontent.com/40470811/200471254-473ffba5-449d-4736-8230-f35ca0037ad7.png">

 
[latest.log](https://github.com/Kasax007/Modpack-Development/files/9957459/latest.log)
pastebin says file too big

only mods added are ones that effect the player model, xray, and a lod mod for seeing distant terrain in very poor resolution.
I have tested with these disabled, no effect.

**Comment by Kasax007** [comment]
I assume you couldn't break blocks anymore and the world wasn't running at all basically?

**Comment by DougStoker** [comment]
yeah

**Comment by royaljacques** [comment]
personally having allocated 20 gb of ram to the server, the chunks no longer loaded correctly. I would suggest that during the first loading we load 50k /50 of blocks on the shelf to reduce the loss of fps
I don't know if a mod can do this.

**Comment by DougStoker** [comment]
i tried using https://www.curseforge.com/minecraft/mc-mods/chunky-pregenerator to generate a 10km radius but the internal server stopped sending any packets around 5%
