### ISSUE TITLE
Spectrum Reed not spawning due to Terralith disabling them

### ISSUE THREAD

**Issue by ShadowMagnus000** [Kasax007/Dreamcraft-Development-#60]
The Spectrum Reeds do not spawn on any generated world due to Terralith preventing them from being generated in any world. This halts the progression of the mod because there are no other ways to acquire them. Spectrum Reeds grow on Clay blocks but Terralith prevents this. A solution would be to modify Terralith's parameters to allow the Spectrum Reeds to spawn or to add a custom recipe on the modpack itself so that progression through spectrum may continue.

**Comment by Kasax007** [comment]
Can you find those Reeds in the mining dimension?

**Comment by willstickles** [comment]
I believe the mermaid tears might fall under the same issue. I have searched the oceans for 2 days and have not found one spawn yet.
