### ISSUE TITLE
[Feature Request] Scripting language

### ISSUE THREAD

**Issue by togreglove** [Kasax007/Dreamcraft-Development-#61]
**Describe the bug**
Unable to create zenscript or kube.js scripts

**To Reproduce**
1. Try to find scripting mod
2. Fail

**Expected behavior**
Being able to add/modify/remove recipes and do other scripting related things.

**Comment by Kasax007** [comment]
I think if you try to add those mods manually you should be able to. Or craft tweaker might also work. Let me know if they do. Also I am curious if you do get them to work what you want to script into the game :D

**Comment by togreglove** [comment]
Mainly I would use it, as a person that hosts the pack, to change or remove recipes. We can't get the reeds in Spectrum, so we were going to add a recipe to make them instead, and found no scripting language.

**Comment by Kasax007** [comment]
Hey, did you ever add a scripting language and did some scripting? I am asking since I want to add that for the next update :)
