### ISSUE TITLE
travelling planets

### ISSUE THREAD

**Issue by sgage13** [Kasax007/Dreamcraft-Development-#62]
as soon as you try to travel to any planet/moon game just goes black screen and crash but stays running in background does not give a crash report since it does not actually crash

**Comment by shinji257** [comment]
Do you have shaders enabled?

**Comment by sgage13** [comment]
we disabled before launch

**Comment by sgage13** [comment]
it is as soon as you click any planet other than earth

**Comment by Kasax007** [comment]
Try on the latest version of the pack, Ad astra got an update and maybe fixed this problem.

**Comment by Kasax007** [comment]
closed due to no response. Feel free to reopen
