### ISSUE TITLE
Suggestion: Blacklist Spectrum/Ad Astra/Gobber2 mods from Spatial Harvester void mining

### ISSUE THREAD

**Issue by shinji257** [Kasax007/Dreamcraft-Development-#63]
Spectrum, Ad Astra, and Gobber2 mods should probably be blocked from Spatial Harvester spawning them in.  Spectrum gives ores that you do not know about so it shows as gibberish and potentially allows you to get items that you shouldn't have.  Ad Astra trivializes going into space (partially due to a separate infinite power bug).  Gobber2 bypasses the need to have netherite to mine it because you can smelt the ores once you have it.

Alternatively for Gobber2 disable the smelting recipes.

**Comment by Kasax007** [comment]
Good point. I will look into that for future updates. Appreciate it.

**Comment by shinji257** [comment]
These are the changes to this mod that we are doing on our server install.  You can take any, all, or none of the changes as I did them for future pack updates.  It disables spectrum and ad_astra ore generation, slows down the Tier 8 harvesters and the Mob Harvesters.  Tier 8 goes from 4x per sec to 1x per sec for ore generation which is still 5x faster than Tier 7.  The Mob Harvesters spawn items at a rate matching the Tier 1 harvesters.  Gobber ores are being gated between Harvester Tiers 6-8 for each successive tier of Gobber ore.  Tier 6 is the normal ore you get from the overworld, Tier 7 for nether ore, and Tier 8 for end ore.  Ancient Debris is gated to Tier 6.
```
"blacklist_ores_mod"=[
    [
        spectrum,
        ad_astra
    ]
]
"min_tier_ores"=[
    [
        gobber2,
        "gobber2_ore",
        6
    ],
    [
        gobber2,
        "gobber2_ore_nether",
        7
    ],
    [
        gobber2,
        "gobber2_ore_end",
        8
    ],
    [
        minecraft,
        "ancient_debris",
        6
    ]
]
"speed_bio_8"=20
"speed_dark_mob"=400
"speed_ore_8"=20
"speed_soil_8"=20
"speed_specific_mob"=400
"speed_stone_8"=20
```

**Comment by Kasax007** [comment]
Thanks for sharing this with me. I assume this is just the config file for the spatial harvesters? Or is this implemented with kubeJS or something like that?

**Comment by shinji257** [comment]
This is just the config file for spatial harvesters and only the changes I made to it.
