### ISSUE TITLE
Axolotls keep crashing my game

### ISSUE THREAD

**Issue by OutroEgo** [Kasax007/Dreamcraft-Development-#70]
**Describe the bug**
Any time I go near a place that spawns axolotls (such as lush caves), my game freezes and crashes. I've also gotten a crash from the minimap mod about the axolotls too. 

**To Reproduce**
Go to lush caves or anywhere that spawns in axolotls and crash i guess.

**Expected behavior**
Axolotls not crashing my game.

**Screenshots + Crash log**
[crash-2022-12-10_19.49.06-client.txt](https://github.com/Kasax007/Modpack-Development/files/10204047/crash-2022-12-10_19.49.06-client.txt)
[crash-2022-12-10_19.54.18-client.txt](https://github.com/Kasax007/Modpack-Development/files/10204048/crash-2022-12-10_19.54.18-client.txt)
[crash-2022-12-11_21.11.37-client.txt](https://github.com/Kasax007/Modpack-Development/files/10204049/crash-2022-12-11_21.11.37-client.txt)

1. First txt is about the minimap
2.  Second one is about an axolotl
3.  Third one is the most recent crash

**Version of the modpack**
Dreamcraft 1.19.2-1.0.31

**Additional context**
When I rejoin, I spot the axolotl and its just a regular pink.

**Comment by Kasax007** [comment]
Remove the mod more axolotl variants :) Mavm or something like that is the jar file called

**Comment by GeorgeWL** [comment]
@Kasax007 since you've removed the mod in latest version, makes sense to just close this issue IMO as "will not fix"

**Comment by Kasax007** [comment]
Forgot to close this. Thanks for the reminder :)
