### ISSUE TITLE
modpack update list

### ISSUE THREAD

**Issue by Giro100** [Kasax007/Dreamcraft-Development-#76]
performance:
www.9minecraft.net/open-parties-and-claims-mod
www.9minecraft.net/very-many-players-mod
www.9minecraft.net/smooth-chunk-save-mod
www.9minecraft.net/no-recipe-book-mod

items:
www.9minecraft.net/iron-generators-mod
www.9minecraft.net/solar-generation-mod
www.9minecraft.net/powah-mod
www.9minecraft.net/iron-chests-restocked-mod - can be locked and transported
www.9minecraft.net/waystones-mod - different one
www.9minecraft.net/iron-coals-mod
www.9minecraft.net/diagonal-fences-mod

**Comment by Giro100** [comment]
https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod
https://www.curseforge.com/minecraft/mc-mods/four-elemental-swords
https://www.curseforge.com/minecraft/mc-mods/portal-gun-fabric
https://www.curseforge.com/minecraft/mc-mods/miskatonic-mysteries/screenshots

**Comment by Archiplex** [comment]
Would love to see a little more magic to shore up the smaller magic section of the modpack, i.e  https://www.curseforge.com/minecraft/mc-mods/botania-fabric

Origins is also generally a very adored mod with Fabric packs- adding races to the game can completely redefine how you play the game (i.e as a merling). Some can be a little broken, but I think they're some of the coolest things in modern minecraft.
https://www.curseforge.com/minecraft/mc-mods/origins
+ https://www.curseforge.com/minecraft/mc-mods/origins/relations/dependents?filter-related-dependents=3 for a decent list of other addons that require it (usually just adding more options is all).


Paradise Lost is also a great revival of the Aether that's made for fabric: https://www.curseforge.com/minecraft/mc-mods/paradise-lost


A friend of mine also suggested Respawnable Pets due ot the amount of taming-related mods in this pack:
https://www.curseforge.com/minecraft/mc-mods/respawnable-pets

**Comment by Cora-Speaking** [comment]
Would love to see MCA reborn in this pack! Not many packs have it and I think it make villagers way more immersive and fun to interact with. I don't know of many mods that conflict with it. 
Here's the link: https://www.curseforge.com/minecraft/mc-mods/minecraft-comes-alive-reborn
Also the cosmetic armor mod is a must!
https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-fabric/files

**Comment by Giro100** [comment]
increases the max enchantment level:
https://9lifehack.com/enchantsplus-minecraft-mc-mods.p311792

The Twilight Forest: 
https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest

Entities movement:  
https://www.curseforge.com/minecraft/mc-mods/carry-on

i dont know which powah like is better:
https://www.curseforge.com/minecraft/mc-mods/powah-rearchitected

Server Performance :
https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save

**Comment by Giro100** [comment]
pls add those to the next beta:

TARDIS:
https://www.curseforge.com/minecraft/mc-mods/tardis-refined

increases the max enchantment level:
https://www.curseforge.com/minecraft/mc-mods/enchantsplus

Entities movement:
https://www.curseforge.com/minecraft/mc-mods/carry-on

Portal gun:
https://www.curseforge.com/minecraft/mc-mods/portal-cubed

Mekanism:
https://www.curseforge.com/minecraft/mc-mods/mekanism

items transfer and energy storage:
https://www.curseforge.com/minecraft/mc-mods/integrated-dynamics

Cosmetic Armor:
https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-fabric

**Comment by Giro100** [comment]
maybe replace the croparia mod with the mystical agriculture:
https://www.curseforge.com/minecraft/mc-mods/mystical-agriculture

**Comment by Kasax007** [comment]
Added whats available for fabric and fits the dynamic of the pack.
