### ISSUE TITLE
Very Many Players mod causes random number of instant disconnects

### ISSUE THREAD

**Issue by ahribellah** [Kasax007/Dreamcraft-Development-#77]
**Describe the bug**
The Very Many Players mod causes a random number of instant disconnects before allowing users to connect.

**To Reproduce**
1. Install v6 of the modpack.
2. Attempt to connect to your server.

**Expected behavior**
Players connect without issue.

**Screenshots + Crash log**
Nothing. I had to do a binary search to figure out what was causing the problem.

**Version of the modpack**
Fabric 1.19.2 v6

**Additional context**
Seems like this was fixed in a later version of the mod. Updating should fix it.

**Comment by Kasax007** [comment]
Fixed for the upcoming version of the modpack. (Hopefully due to updating) :D
