### ISSUE TITLE
end gobber machete quest broken in quest explorer

### ISSUE THREAD

**Issue by Azepto** [Kasax007/Dreamcraft-Development-#79]
Describe the bug A clear and concise description of what the bug is.

**To Reproduce Steps**
Go in the FTB quest explorer and view the quest called "harvest_scythes:gobber2_machete_end"
Have an End Gobber Machete in your inventoru
The quest cannot be completed and is visibly broken within FTB quest

**Expected behavior**
The quest has a normal name instead of the item id and is completed upon acquiring the item

**Screenshots + Crash log If applicable**
![image](https://user-images.githubusercontent.com/116595753/212562685-8b914c6b-a6e0-4508-a40f-10ae2354ffce.png)

**Version of the modpack** 
Fabric 1.19.2 v6

**Comment by Kasax007** [comment]
Fixed for the next update
