### ISSUE TITLE
EV transformer from tech reborn is uncraftable and unobtainable

### ISSUE THREAD

**Issue by Azepto** [Kasax007/Dreamcraft-Development-#80]
**Describe the bug**
The EV Transformer item from tech reborn cannot be obtained or crafted AND is required for quest progression and chapter completion

**To Reproduce**
View the recipe in JEI of the EV Transformer. id: "techreborn:ev_transformer"
No recipes or way to acquire the item are listed.

**Expected behavior**
The item should either be craftable/obtainable or removed from quest progression

**Screenshots + Crash log**
![image](https://user-images.githubusercontent.com/116595753/212563194-ad173220-38dc-4362-af23-d2f98d4deeab.png)

**Version of the modpack**
Fabric 1.19.2 v6

**Additional context**
The item is uncraftable in Tech Reborn by default and is a creative only item. I think simply removing the quest is the correct way to fix this issue, as adding it to the "creative only" items requiring quest keys would not be worth it considering the other items available and the very specific use of this item.

**Comment by Kasax007** [comment]
Fixed for the upcoming update
