### ISSUE TITLE
"collect every globe" quest from Ad Astra is uncompletable

### ISSUE THREAD

**Issue by Azepto** [Kasax007/Dreamcraft-Development-#81]
**Describe the bug**
The quest "Collect every globe" requires the player to collect every globe in the Ad Astra mod, however this is impossible because every globe other than the moon globe is a creative only item and is unobtainable in survival

**To Reproduce**
view the "Collect every globe" quest in the FTB quest explorer, located in the Space Exploration chapter

**Expected behavior**
Either remove the quest or add a way to obtain the globes in survival

**Screenshots + Crash log**
![image](https://user-images.githubusercontent.com/116595753/212563481-14dccc02-9f75-424f-8755-039e983caa0d.png)

**Version of the modpack**
Fabric 1.19.2 v6

**Additional context**
Since the moon globe is the first obtainable globe and can be obtained multiple times, I would suggest adding a crafting recipe for the other planets' globes using the moon globe and items from the planet you want to get the globe of.

**Comment by Kasax007** [comment]
Fixed for the upcoming update
