### ISSUE TITLE
Issue joining LAN game

### ISSUE THREAD

**Issue by JustABea** [Kasax007/Dreamcraft-Development-#82]
**Describe the bug**
Im having an issue with joining a LAN game with my partner and vice versa

io.netty.handler.codec.DecoderException: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:t? 

try to join a LAN world 

[latest.log](https://github.com/Kasax007/Modpack-Development/files/10452324/latest.log)

dream craft version - 1.0.34
fabric version - 0.14.12
MC version 1.19.2
 
we are both getting the exact same issue and logs when trying to join each other but the game runs fine single player.

Ive spent hours and I understand there are files with incorrect characters, I just cant find where or a fix to it.

**Comment by Hypersonicx** [comment]
We have exactly the same problem. To work around the error, you need to set up a local server on one of the two computers. Works fine for us.

**Comment by Kasax007** [comment]
Do you wish to play in a LAN world with a friend in your own network but are having trouble connecting? 
Create a server with my server pack, and use "localhost" as the IP address to connect to it. It will allow you to play with each other and even gives you a better performance. To set up the server, go to https://www.curseforge.com/minecraft/modpacks/dreamcraft-new/files and download the server pack. Make sure to get the same version as your client.

**Comment by jjs98** [comment]
It would be great if the LAN problem can be fixed so there is no need to setup a dedicated server
