### ISSUE TITLE
Obsidian Axe from Croparia is not craftable

### ISSUE THREAD

**Issue by TobiasAlexanderWulff** [Kasax007/Dreamcraft-Development-#86]
The "Obsidian Axe" from Croparia is not craftable like all other obsidian tools (pickaxe, sword, shovel, etc.).

1. Open Inventory.
2. Type Obsidian Axe into the searchbar.
3. Left-click on the item. -> No recipe shows up.

**Comment by Kasax007** [comment]
Fixed for the upcoming update
